"""create_prospects_table

Revision ID: 2a2cbc492ca6
Revises: 
Create Date: 2026-06-24 15:09:07.425317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a2cbc492ca6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('pays', sa.String(length=100), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('adresse_web', sa.String(length=255), nullable=False),
    sa.Column('email_contact', sa.String(length=255), nullable=False),
    sa.Column('linkedin_contact', sa.String(length=255), nullable=True),
    sa.Column('nom_contact', sa.String(length=255), nullable=False),
    sa.Column('poste_contact', sa.String(length=255), nullable=False),
    sa.Column('nb_chambres', sa.Integer(), nullable=True),
    sa.Column('capacite_description', sa.Text(), nullable=True),
    sa.Column('presence_booking', sa.Boolean(), nullable=False),
    sa.Column('note_booking', sa.Float(), nullable=True),
    sa.Column('presence_expedia', sa.Boolean(), nullable=False),
    sa.Column('score_activite_digitale', sa.Integer(), nullable=False),
    sa.Column('score_coherence_marche', sa.Integer(), nullable=False),
    sa.Column('score_taille_capacite', sa.Integer(), nullable=False),
    sa.Column('score_contact_decideur', sa.Integer(), nullable=False),
    sa.Column('score_liberte_ota', sa.Integer(), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('commission_standard', sa.Float(), nullable=False),
    sa.Column('commission_plancher', sa.Float(), nullable=False),
    sa.Column('langue', sa.String(length=5), nullable=False),
    sa.Column('date_ajout', sa.Date(), nullable=False),
    sa.Column('date_prochain_contact', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adresse_web')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prospects')
    # ### end Alembic commands ###
