"""create_scan_jobs_table

Revision ID: 3f9f89c17064
Revises: 2a2cbc492ca6
Create Date: 2026-06-24 15:59:01.090884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f9f89c17064'
down_revision: Union[str, None] = '2a2cbc492ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('pays', sa.String(length=100), nullable=False),
    sa.Column('type_partenaire', sa.String(length=50), nullable=False),
    sa.Column('limite', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('nb_trouves', sa.Integer(), nullable=False),
    sa.Column('nb_ajoutes', sa.Integer(), nullable=False),
    sa.Column('nb_veille', sa.Integer(), nullable=False),
    sa.Column('nb_doublons', sa.Integer(), nullable=False),
    sa.Column('progression', sa.Integer(), nullable=False),
    sa.Column('erreur', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_jobs')
    # ### end Alembic commands ###
